### PR TITLE
[Porting from cAVS driver] cAVS driver notifies FW to work in DMA scheduling

### PR DESCRIPTION
**Pull request by libinyang**
cAVS driver notifies FW to work in DMA scheduling

Tracked-On: OAM-117352

### CODE REVIEW

**Review by crojewsk-intel — CHANGES_REQUESTED** [review]
Author for the first commit ("ASoC: Intel: avs: Expose FW version and modules info with sysfs") has been modified. Please revert to the original one.

Another thing are the `Tracked-On:` tags. These are non-standard and the relevant tickets cannot be accessed publicly. Because of that, I believe the tags should be removed when sending patches to public repository which projectceladon is.

**Comment by libinyang** [comment]
> Author for the first commit ("ASoC: Intel: avs: Expose FW version and modules info with sysfs") has been modified. Please revert to the original one.
> 
> Another thing are the `Tracked-On:` tags. These are non-standard and the relevant tickets cannot be accessed publicly. Because of that, I believe the tags should be removed when sending patches to public repository which projectceladon is.

@crojewsk-intel Thanks. The Auther issue has been fixed. And as we talked in last meeting, 'Tracked-On' is required by the patch merge processing and currently we have to do so otherwise the patches won't be merged.

**Comment by crojewsk-intel** [comment]
Commit `ASoC: Intel: avs: Expose FW version and modules info with sysfs` seems to be out of place. Even if it's needed for this port, I'd recommend the upstream equivalent \[1\] instead. In regard to `ASoC: Intel: avs: PHRASE_DETECTED propagation`, it's almost definitely out of place - this PR relates to DMA_SCHEDULER configuration and not the WakeOnVoice functionality.

\[1\]: https://lore.kernel.org/r/20240209085256.121261-1-amadeuszx.slawinski@linux.intel.com

**Comment by libinyang** [comment]
changelog:
1. "ASoC: Intel: avs: Expose FW version and modules info with sysfs" is using upstreaming patch
2. removed 2 unnecessary patch: 0002-ASoC-Intel-avs-PHRASE_DETECTED-propagation.patch and 0003-ASoC-Intel-avs-Notify-userspace-waiting-for-keyprase.patch

**Review by crojewsk-intel — APPROVED** [review]
Apart from `Tracked-On:` tags which point to articles not available to the public at all, looks good.

**Review by JeevakaPrabu — APPROVED** [review]

**Pull request merged**
