### PR TITLE
touchscreen/ef1e_tp: Fix kernel panic issue when there is no serdes screen present

### PR DESCRIPTION
**Pull request by phreer**

### CODE REVIEW

**Review by JeevakaPrabu — COMMENTED** [review]
LGTM

**Review by kaushlen — APPROVED** [review]

**Review by kaushlen — APPROVED** [review]

**Review by JeevakaPrabu — APPROVED** [review]

**Review by YuanjunHuang — COMMENTED** [review]
LGTM. nice fix!

**Review by YuanjunHuang — COMMENTED** [review]
nice fix!

**Review by feijiang1 — APPROVED** [review]
LGTM

**Pull request merged**
