### PR TITLE
dwc3: set as high speed device

### PR DESCRIPTION
**Pull request by qizhangz**
Tracked-On: OAM-112914

### CODE REVIEW

**Comment by qizhangz** [comment]
@vilasrk @sgnanase would you please review this PR? Thank you!

**Review by vilasrk — CHANGES_REQUESTED** [review]
This will cause Coverity issue.
The indicated dead code may have performed some action; that action will never occur.

https://coverityent.devtools.intel.com/prod2/#/project-view/20221/10707?selectedIssue=304546

for your reference.

**Comment by qizhangz** [comment]
> This will cause Coverity issue. The indicated dead code may have performed some action; that action will never occur.
> 
> https://coverityent.devtools.intel.com/prod2/#/project-view/20221/10707?selectedIssue=304546
> 
> for your reference.

done. @vilasrk

**Comment by qizhangz** [comment]
@vilasrk @sgnanase can you please review this PR?

**Review by vilasrk — APPROVED** [review]
LGTM

**Review by sgnanase — APPROVED** [review]

**Review by vilasrk — APPROVED** [review]
LGTM

**Pull request merged**
